version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"

  # Maintain dependencies for pub
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
